Etpa\Domain\Story:
  type: entity
  table: story
  repositoryClass: Etpa\Infrastructure\Persistence\Doctrine\DoctrineStoryRepository
  id:
    id:
      type: string
      generator:
        strategy: NONE
  fields:
    title:
      type: string
      length: 250
    description:
      type: text
    status:
      type: integer
    rating:
      type: integer
      nullable: true
    votes:
      type: integer
  oneToMany:
    pages:
      targetEntity: Etpa\Domain\Action
      mappedBy: story
